### ISSUE TITLE
undefined error in firefox for viewbox.baseVal

### ISSUE THREAD

**Issue by dp-huang** [DanielHoffmann/jquery-svg-pan-zoom#15]
when integrating this cool library to my project, I realized there is a minor issue in firefox that raises an undefined error blocking the zoom events,

in line 318 of jquery.svg.pan.zoom.js,
        vb = $.extend({}, this.viewBox.baseVal);

vb.x, vb.y, vb.width. vb.height are all undefined.

**Comment by DanielHoffmann** [comment]
Hi Huang, does this issue only happen in firefox? Well some sanity checking on that vb guy is in order anyway. I will add this check and make a new version 1.0.3 today or tomorrow.

I am glad you liked my library, might I ask how you found out about this project? I did not exactly publish it anywhere

**Comment by dp-huang** [comment]
Yes, this undefined error just happens in Firefox as my test. Actually I
searched my requirement in Stackoverflow and some posts redirect me to your
library.

2015-10-09 16:23 GMT+08:00 Daniel Hoffmann Bernardes <
notifications@github.com>:

**Comment by DanielHoffmann** [comment]
Sorry for the delay Huang, the bug is fixed and a new version (1.0.3) is in the repository and also available over bower. Where are you planning to use this on?
