### ISSUE TITLE
initialViewBox as object is not working

### ISSUE THREAD

**Issue by DanielHoffmann** [DanielHoffmann/jquery-svg-pan-zoom#4]
In (line 317)[https://github.com/DanielHoffmann/jquery-svg-pan-zoom/blob/c313/src/jquery.svg.pan.zoom.coffee#L317] the vb variable is never null

**Comment by tomek-he-him** [comment]
And what exactly does [line 310](https://github.com/DanielHoffmann/jquery-svg-pan-zoom/blob/c313/src/jquery.svg.pan.zoom.coffee#L310) mean?

**Comment by DanielHoffmann** [comment]
@tomekwi hm I don't remember exactly, I just found this bug, its being some time since I last played with this. Sorry I did not had the opportunity to improve this plugin this week because I had my wisdom teeth removed, I need to do some major cleanups to the code and merge your changes (and I can't just merge without testing with my own project first)

**Comment by tomek-he-him** [comment]
@DanielHoffmann fair enough. To be honest, I'm also quite tied up at the moment. The project I'm working on needs to speed up, and it's possible that I won't have time to implement panning and zooming just yet.

All PRs I've submitted are ready to merge.
